---
kind: Service
apiVersion: v1
metadata:
  name: mongo
  namespace: laf
spec:
  # clusterIP: None
  selector:
    app: mongo
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017

### This mongodb ONLY work for demo purpose, you should config your own volume for production use!
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: laf
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  serviceName: "mongo"
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: bitnami/mongodb:5.0
          name: mongo
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: MONGODB_REPLICA_SET_MODE
              value: primary
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: mongo.laf
            - name: MONGODB_REPLICA_SET_NAME
              value: laf
            - name: MONGODB_REPLICA_SET_KEY
              value: replicasetkey123
            - name: MONGODB_ROOT_PASSWORD
              value: password123
            - name: MONGODB_USERNAME
              value: my_user
            - name: MONGODB_PASSWORD
              value: password123
            - name: MONGODB_DATABASE
              value: sys_db
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /bitnami/mongodb
              name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
